### PR TITLE
Fix/graph axis

### LINKED ISSUE #98: Fix output graphs' x axis
The output graphs' x-axis is showing nonrounded days values. It could be changed to show rounded values such as 100, 150, 200 days, etc. The final value showed on the x-axis is different between graphs.
image

### PR DESCRIPTION
**Pull request by MerlinEgalite**
Fix #98, #97

### CODE REVIEW

**Review by marthendalnunes — COMMENTED** [review]
It would be nice to have some responsiveness. In this case, independently of the amount of the days, the width of the graph would be the same, so if there be just 250 timesteps we will have 10 days tick points, but if we have 2500 timesteps, it would be 100 tick points, what will visually pollute the graph. I suggest define a fixed amount of tick points and then split it rounded by the amount of the timesteps of the graphs.

**Comment by MerlinEgalite** [comment]
Screenshot 2021-01-08 at 21 10 48

Now it takes the first element of the following list that allows us to have a maximum of 20 ticks (a value we can change but I think 20 is good)

File: src/views/results/Results.vue [hunk 1]
```diff
@@ -227,6 +227,15 @@ export default {
             yAxes: input.yAxes,
             xAxes: [
               {
+                ticks: {
+                  autoSkip: false,
+                  maxTicksLimit: 20,
```
Comment (mendesfabio) [inline src/views/results/Results.vue:232]: Since we have more space between the ticks, you could make the text horizontal. Just add the following params.

```
maxRotation: 0,
minRotation: 0,
```

**Review by mendesfabio — COMMENTED** [review]
Hey @Merlin, I liked your work here. Could you add these ticks params on Level 5 too? There I think the interval should be 10 days.

File: src/views/results/Results.vue (hunk 1 above)
Comment (MerlinEgalite) [reply src/views/results/Results.vue:232]: You're right! it'll be better

**Comment by MerlinEgalite** [comment]
I update level 5-1 with the variable feature (as in the results page) in case we change the code in the future and the timeframe is increased or decreased. Should be good now!

**Review by mendesfabio — APPROVED** [review]
LGTM!
